#program to input eight numbers from the user and display all th unique numbers(once.)
n2= int(input("enter number 1"))
n3= int(input("enter number 2"))
n4= int(input("enter number 3"))
n5= int(input("enter number 4"))
n6= int(input("enter number 5"))
n7= int(input("enter number 6"))
n8= int(input("enter number 7"))
s={n2,n3,n4,n5,n6,n7,n8}
print(s)